### ISSUE TITLE
Problem opening DB URL in PS7

### ISSUE THREAD

**Issue by rcarpenter79** [panteam-net/pt.KeePass#3]
When calling KeePassLib.PwDatabase.Open() when the database is using a URL it fails with the message
```
MethodInvocationException: Exception calling "Open" with "3" argument(s): "The filename, directory name, or volume label syntax is incorrect. :  '<path>'"
```
The path that is displayed is the current working directory joined to the URL.

This only happens when using PS 7.
When I run the same command in PS5 it opens the database.

I'm testing using 
PS - 7.2.4
pt.KeePassLibStd - 2.50.0.4849
SkiaSharp - 2.80.3.0
System.Security.Cryptography.ProtectedData - 6.0.21.52210

Thanks

**Comment by ArtjomP** [comment]
It looks like you need to put you path into the quotes "path".
